# Generated by Django 4.1.7 on 2023-03-11 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoutout', '0002_shoutouts_is_published'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='orders',
            name='shoutout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoutout.shoutouts'),
        ),
    ]
