# Generated by Django 4.1.7 on 2023-03-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoutout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoutouts',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
