# Generated by Django 4.1.7 on 2023-03-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoutout', '0002_shoutouts_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoutouts',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='shoutouts',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='shoutouts',
            name='user_profile_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
